### ISSUE TITLE
Нужно добавить ссылки на создание схем для сайтов

### ISSUE THREAD

**Issue by allakin** [iVaeum/new.page#14]
Я думаю их запихнуть в категорию "Разработка"
Ссылки: 
https://wireframe.cc/
https://www.draw.io/

**Comment by vaeum** [comment]
на счет категории "разработка", я думаю сделать ее не так как основные вкладки
потому что там много ссылок нужно добавлять, и категориио там будут
я предлогаю сделать чтото на подобие как у bootstrap
скрин 
![2015-01-15 12 00 28](https://cloud.githubusercontent.com/assets/6481202/5754827/5ce8eb0a-9ca6-11e4-9def-51bdde3936f8.png)

**Comment by allakin** [comment]
Да давай
